"""Base LLM provider interface for skill generation.

Defines the abstract interface for LLM providers that generate skills
from capability descriptions. Project B will extend this interface.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass
class SkillPackage:
    """A complete skill package generated by an LLM.

    Contains all artifacts needed to write a skill to staging:
    - name: The skill name (must match manifest name)
    - code: The skill.py source code
    - manifest: The skill.json manifest as a dict
    - tests: Optional list of test file contents
    """

    name: str
    code: str
    manifest: dict
    tests: list[str]


class LLMProvider(ABC):
    """Abstract base class for LLM providers that generate skills.

    Implementations must provide generate_skill() to create skill packages
    from natural language capability descriptions.
    """

    @abstractmethod
    def generate_skill(self, capability: str, context: str = "") -> SkillPackage:
        """Generate a skill package from a capability description.

        Args:
            capability: Natural language description of the desired capability.
            context: Optional additional context (e.g., from the log line).

        Returns:
            SkillPackage containing name, code, manifest, and tests.

        Raises:
            ValueError: If the capability cannot be fulfilled.
        """
        pass

    # ==========================================================================
    # Project B Extension Points (commented out for now)
    # ==========================================================================
    #
    # def merge_skills(self, skills: list[str]) -> SkillPackage:
    #     """Merge multiple similar skills into one.
    #
    #     Used by Project B's batch evolution to consolidate redundant skills.
    #
    #     Args:
    #         skills: List of skill names to merge.
    #
    #     Returns:
    #         A new SkillPackage that combines the functionality.
    #     """
    #     raise NotImplementedError("merge_skills is a Project B feature")
    #
    # def assess_similarity(self, skill_a: str, skill_b: str) -> float:
    #     """Assess semantic similarity between two skills.
    #
    #     Used by Project B for tool deduplication decisions.
    #
    #     Args:
    #         skill_a: First skill name.
    #         skill_b: Second skill name.
    #
    #     Returns:
    #         Similarity score between 0.0 (different) and 1.0 (identical).
    #     """
    #     raise NotImplementedError("assess_similarity is a Project B feature")
